on:
  schedule:
  - cron: "0 3 * * *"

name: update-data

jobs:
  render:
    name: update-data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgload
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("remotes")
          remotes::install_local(".")
          remotes::install_cran("readxl")
          remotes::install_cran("writexl")
          remotes::install_cran("usethis")
          remotes::install_cran("rmarkdown")
          remotes::install_cran("pkgdown")
        shell: Rscript {0}

      - name: Execute Script
        run: |
          Rscript data-raw/atualizar_dados.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/.
          git add README.md
          git add README.Rmd
          git add docs/.
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
