on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

name: update-data
jobs:
  render:
    name: update-data
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.3"

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Instalando libs de sistema
        run: |
          sudo apt update
          sudo apt install -y \
            libudunits2-dev libgdal-dev libprotobuf-dev protobuf-compiler \
            libjq-dev libgit2-dev libcurl4-openssl-dev libcurl4-gnutls-dev curl \
            libssl-dev libxml2-dev

      - name: Instalando pacotes R básicos
        run: |
          Rscript -e "install.packages('remotes', repos = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest')"
          Rscript -e "install.packages(c('devtools', 'usethis'), repos = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest')"

      - name: Execute Script
        run: |
          Rscript data-raw/atualizar_dados.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . || echo "Sem alteracoes"
          git commit -m 'Atualizando dados' || echo "Sem alteracoes"
          git push origin || echo "Sem alteracoes"
